# Generated by Django 3.2.5 on 2021-08-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profiles', '0011_alter_friendship_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=200)),
                ('seen', models.BooleanField(default=False)),
                ('tobe_shown', models.BooleanField(default=True)),
                ('target_url', models.URLField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiles.profile')),
                ('notifying', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_notifications', to='Profiles.profile')),
            ],
        ),
    ]
