# Generated by Django 3.2.5 on 2021-08-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
