# Generated by Django 3.2.5 on 2021-08-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_alter_notification_target_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, choices=[('like', 'like'), ('comment', 'comment'), ('request received', 'request received'), ('request accepted', 'request accepted')], max_length=16),
        ),
    ]
