# Generated by Django 3.2.5 on 2021-07-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0010_auto_20210730_2005'),
        ('Profiles', '0008_alter_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
