# Generated by Django 3.2.5 on 2021-08-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0010_friendship_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('accepted', 'accepted')], default='sent', max_length=8),
        ),
    ]
