# Generated by Django 3.2.5 on 2021-07-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0006_alter_profile_user'),
        ('Posts', '0006_comment_post_postlike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostLike',
            new_name='Like',
        ),
    ]
